### ISSUE TITLE
I want to generate a heightmap from a mesh.

### ISSUE THREAD

**Issue by IvanMax3212** [bshishov/UnityTerrainErosionGPU#1]
I am going to replace your current terrain data with Tycoon terrain system.
To make the water compatible with the changed terrain, I had to generate a different heightmap with that mesh. But I don't know how to do it. Can't find the solution in google.
My issue : Mesh -> Heightmap

**Comment by bshishov** [comment]
The question is beyond the scope of the project.

If your terrain system is based on Unity native terrain system, you can simply access the heightmap of that. See the properties of TerrainData: [TerrainData-heightmapTexture](https://docs.unity3d.com/ScriptReference/TerrainData-heightmapTexture.html)

Once you get the texture, you need to set the Red channel of state texture with heightmap data from terrain texture. You can do this by operation called [Graphics.Blit](https://docs.unity3d.com/ScriptReference/Graphics.Blit.html). There is a material argument, so create a simple "Copy only red channel" shader, that reads from UnityTerrain Heighmap and writes to [_stateTexture](https://github.com/bshishov/UnityTerrainErosionGPU/blob/master/Assets/Scripts/CustomTerrain.cs#L93) - you have to make it public though.

If you do this in a loop, the water should work fine and terrain would be copied each frame from a native unity terrain.

**Comment by bshishov** [comment]
Take a look at [UnityTerrainAdapter.cs](https://github.com/bshishov/UnityTerrainErosionGPU/blob/master/Assets/Scripts/UnityTerrainAdapter.cs)

I've also added a sample scene into Scenes folder with native unity terrain (no erosion, though)

**Comment by IvanMax3212** [comment]
Hello. bshishov.
The code you used is the normal terrain.
I have to use tycoon terrain system (which is not actually a terrain; it draws a bunch of meshes).
So I want to generate a heightmap based on those meshes.
Thanks.

**Comment by bshishov** [comment]
According to the manual: 
http://vikingcrew.net/Tycoon%20Terrain/Tycoon%20Terrain%20Manual.pdf

their terrain system is based on a unity terrain system.

If it is actually not true, then I can suggest couple ways of integrating any arbitrary mesh into simulatuon:

- dumb way. Access the mesh, create  Texture2D of size that matches mesh grid. Then manually set pixel values to the vertex.y of the mesh. Copy texture data to statetexture using methid described above.
- less dumb and more efficient way. Place an orthographic camera directly above the terrain and set camera frustrum to directly match your mesh bounds. Enable camera depth rendering. Set camera's render target 
to a new heightmap RenderTexture with depth. Set an unique layer to the terrain and camera. Then copy camera's depth texture to the statetexture using approach, described above.

I won't provide integration with 3rd party libraries so its on your side.

**Comment by IvanMax3212** [comment]
Hello, Thanks for your reply.
My next problem is close the water in its boundaries.
![image](https://user-images.githubusercontent.com/50035118/76676076-afe64a80-660b-11ea-8a50-c913f43146bb.png)
I want to make it like this : 
![image](https://user-images.githubusercontent.com/50035118/76676107-db693500-660b-11ea-9d8a-1b9f358b0c68.png)

**Comment by bshishov** [comment]
Open a new issue
