### ISSUE TITLE
How to fix the boundaries of water?

### ISSUE THREAD

**Issue by IvanMax3212** [bshishov/UnityTerrainErosionGPU#2]
Today I am going to close the boundaries of water of this terrain erosion gpu project.
At first, it seems possible to make the WATER_HEIGHT(boundary points) = 0f to implement it but it didn't. Is there anyone who have the solution of it?

**Comment by bshishov** [comment]
Hello,

setting WATER_HEIGHT to 0 at boundaries would affect simulation significantly - water will start disappear at the edges.

I'd rather do it this way:
- Create a new vertical plane for each side of the terrain matching resolution of the water plane such that uv coordinates can distinguish between upper vertices (that match water) and lower vertices (that touch terrain)
- Copy/paste water rendering code and set height of lower vertices to TERRAIN_HEIGHT, and upper to WATER_HEIGHT

![sides](https://user-images.githubusercontent.com/4918505/76700767-c48a1780-66cb-11ea-99d8-3cf1812da946.png)

**Comment by IvanMax3212** [comment]
Can you provide me the solution?
I feel thanks if you upload the files.
Greetings. Ivan.

**Comment by IvanMax3212** [comment]
I used this code to get the water height.
Code : (CustomTerrain.cs)

RenderTexture.active = _stateTexture;
tex.ReadPixels(new Rect(0,0,Width,Height), 0,0); //tex : Texture2D
tex.Apply();

But I noticed you set the water height limit to infinitive.
So most of color pixels's green values are 1f (256).
I am going to solve my issue with your first option. 
"Create a new vertical plane for each side of the terrain matching resolution of the water plane such that uv coordinates can distinguish between upper vertices (that match water) and lower vertices (that touch terrain)"

Thanks. Ivan.

**Comment by IvanMax3212** [comment]
I tried myself, but as you can see the quality is really bad.
I think we should solve this problem by using shader. isn't it?
Thanks.
![image](https://user-images.githubusercontent.com/50035118/76831311-d5c15880-6872-11ea-9583-904c9a413c9b.png)

**Comment by bshishov** [comment]
You did a dynamic texture on a static mesh, what I meant was a dynamic mesh)

I will be able to look at this issue on this weekend.

**Comment by bshishov** [comment]
Please see the linked pull-request #3

**Comment by IvanMax3212** [comment]
Hi, bshishov. Really thank you for your great support.
I just have one little problem. That is when I try to scale down/up the water boundary gameobjects, then it crops down like this. What I have to change in code?
1. Currently it looks like this image in unity editor.
![image](https://user-images.githubusercontent.com/50035118/76940294-b5ae9980-6945-11ea-8ad9-cbdfc3f3b4cb.png)
2. When I scale one of the 4 boundaries to it's original size then it looks fine. 
![image](https://user-images.githubusercontent.com/50035118/76940458-0a521480-6946-11ea-8a2f-d8c22480f073.png)

In one word, the shape is absolute.
Thanks Ivan.

**Comment by IvanMax3212** [comment]
Oh, I found the solution. It's simply fixed by changing like the following code.
Material.SetVector("_WorldScale", Size / 4f);

I am going to close this issue when I fix this problem.
![image](https://user-images.githubusercontent.com/50035118/76943894-ccf08580-694b-11ea-878f-37a687f59f29.png)
How do you think about the solution?

**Comment by bshishov** [comment]
Regarding scale - set the correct scale in the WaterBoundary component in the inspector, no need to change the code.

on the screenshot it looks like that the boundary is ofsetted, make sure u didn't move the boundary object

**Comment by IvanMax3212** [comment]
Yes. You are right. 
Thanks again for your great support.
Ivan.
