### ISSUE TITLE
How to add a custom texture to the water shader?

### ISSUE THREAD

**Issue by RaptorRaptures** [bshishov/UnityTerrainErosionGPU#5]
Hi,

Thank you for this project. Really great work. 

I would like to change the water into looking more like lava and not water. Is it possible to update the Water.shader to use a texture instead of basing it on a color?

Thanks. My knowledge on shaders is limited.

**Comment by bshishov** [comment]
Hello

you have to change the shader code and just use a simple uv sampling yourself.
There are plenty of online tutorials about shader programming in unity.

Please note thath this project is not about rendereing and production-ready game components.
The main scope of the project is erosion simulation.

Please stop spamming me, better spend some time learning shader programming.
