### ISSUE TITLE
Please help me to set my custom texture instead of solid color in the water.

### ISSUE THREAD

**Issue by IvanMax3212** [bshishov/UnityTerrainErosionGPU#7]
For now, I can only change the color of the water.
But what I want is set my custom texture such as lava texture in the water material settings.
That's all my request.
Thanks. Ivan

**Comment by bshishov** [comment]
Hello

you have to change the shader code and just use a simple uv sampling yourself.
There are plenty of online tutorials about shader programming in unity.

Please note thath this project is not about rendereing and production-ready game components.
The main scope of the project is erosion simulation.

Please stop spamming me, better spend some time learning shader programming.
